-- MySQL Script generated by MySQL Workbench
-- Sat Sep 28 19:37:50 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lebotsur
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lebotsur
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lebotsur` DEFAULT CHARACTER SET utf8 ;
USE `lebotsur` ;

-- -----------------------------------------------------
-- Table `lebotsur`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lebotsur`.`users` ;

CREATE TABLE IF NOT EXISTS `lebotsur`.`users` (
  `userID` VARCHAR(20) NOT NULL,
  `guild` VARCHAR(30) NOT NULL,
  `money` DECIMAL(10,2) NULL DEFAULT 0.00,
  `experience` INT(11) NULL DEFAULT 0,
  `level` INT NOT NULL DEFAULT 1,
  `moneyRequests` INT(11) NULL DEFAULT 0,
  `lastMoney` VARCHAR(10) NOT NULL,
  `lastExperience` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`userID`, `guild`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lebotsur`.`experienceToLevel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lebotsur`.`experienceToLevel` ;

CREATE TABLE IF NOT EXISTS `lebotsur`.`experienceToLevel` (
  `level` INT NOT NULL,
  `experience` INT NOT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
